spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw_docs_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: jmr980328
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: docs-center
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

server:
  port: 8082


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true #pageSize=0



feign:
  client:
    config:
      default:
        requestInterceptors:
          - com.jmr.docscenter.feignclient.interceptor.TokenRelayRequestInteceptor
logging:
  level:
    com.jmr.docscenter.feignclient.UserCenterFeignClient: debug